version: 2.1

orbs:
  newman: postman/newman@1.0.0

# executor: newman

working_directory: ~/project
parameters:
  environment:
    type: string
    default: DEV
    description: "Environment to run to"
  service:
    type: string
    default: NA
    description: "Service to run"
steps:
  - checkout
  - newman/newman-run:
      collection: https://api.getpostman.com/collections/${COMPOSITION_COLLECTION_UID}?apikey=${POSTMAN_API_KEY}
      environment: https://api.getpostman.com/environments/${DEV_ENV_UID}?apikey=${POSTMAN_API_KEY}
      additional-options: -n 1 -r htmlextra --reporter-htmlextra-export --reporter-htmlextra-title 'Equip API Run Report' --reporter-htmlextra-displayProgressBar --verbose --ignore-redirects  --reporter-junit-export /project/newman/junit.xml
  - store_test_results:
          path: ~/project/newman      
  - store_artifacts:
      path: ~/project/newman          

# workflows:
#   test:
#     jobs:
#       - run-newman-tests:
#           context: automation
