version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run-newman-tests:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Newman
          command: |
            sudo npm install -g newman
      - run:
          name: Run Newman Tests
          command: |
            newman run https://api.getpostman.com/collections/${COMPOSITION_COLLECTION_UID}?apikey=${POSTMAN_API_KEY} -e https://api.getpostman.com/environments/${DEV_ENV_UID}?apikey=${POSTMAN_API_KEY} --reporters cli,htmlextra,junit --reporter-htmlextra-export /project/newman/report.html --reporter-junit-export /project/newman/junit.xml
      - store_test_results:
          path: ~/project/newman
      - store_artifacts:
          path: ~/project/newman
          destination: newman-report

workflows:
  test:
    jobs:
      - run-newman-tests:
          context: automation
