name: Notify users based on issue labels

on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: tekktrik/issue-labeled-ping@v1
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            user: mayank-equip
            label: migration
            message: Hey {user} - the "{label}" label was applied!
