name: Notify users based on issue labels

on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: wow-actions/label-commands@v1
          with:
             CONFIG_FILE: .github/workflows/blank.yml
             recipients: |
                  migration=@mayank-equip
