# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issues:
      types: [labeled]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
        # This step checks out a copy of your repository.
        - uses: actions/checkout@v3
        # This step references the directory that contains the action.
        - uses: ./.github/actions/hello-world-action
          with:
             recipients: |
                  migration=@mayank-equip
